### ISSUE TITLE
cannot install on vs2017 pro

### ISSUE THREAD

**Issue by yoyoys** [madskristensen/AspNetCoreTemplatePack#1] opened 2017-05-10 07:59 UTC
Tried to install from "Extension and Updates" or Download from Market, still got this error

i get an strange error from vsix installer,
but it;s shows Chinese error message, 
it's means about "Because some requirement condition can't be resolve, can't install this extension to this product"
[image](https://cloud.githubusercontent.com/assets/22124891/25888540/2b2cd822-3599-11e7-9f4b-7b39c2cf0d02.png)

**Comment by yoyoys** [comment] 2017-05-10 08:16
i just edit for more install target, it works for me.
sorry i'm a strater for github, hope this fix if okay #2

**Comment by yoyoys** [comment] 2017-05-10 08:39
i just edit the vsixmanifest file and installed it,
but it's doesn't appear in the dialog box...
![image](https://cloud.githubusercontent.com/assets/22124891/25890177/3698baae-359f-11e7-9e14-de326c82de3e.png)

i'm using vs 2017 15.1(26403.7)
![image](https://cloud.githubusercontent.com/assets/22124891/25890136/05fa98c2-359f-11e7-9106-cb0b22772f05.png)

**Comment by Wonovan** [comment] 2017-05-10 15:09
I was unable to install this yesterday, so when I saw an update come through this morning (5/10/2017) I was hoping that it would resolve the problem. I'm now running VS Enterprise 2017 v15.2 (26430.4) and I still cannot install this. It says that I "the extension cannot be installed to this product due to prerequisites that cannot be resolved".

**Comment by yoyoys** [comment] 2017-05-11 02:29
@Wonovan 
Updated to 20430.4, still same problem here.

And i try to force install(By edit install target), the template still not shows.
(but dotnet new works)

**Comment by madskristensen** [comment] 2017-05-11 23:51
This extension requires VS2017 Community or higher with update 3. It requires update 3 because the hook to get the templates into the ASP.NET project dialog didn't exist before update 3 which was just released in a preview yesterday. 

This is by design

**Closed as completed by madskristensen** 2017-05-11 23:51 UTC
